apiVersion: apps/v1
kind: Deployment
metadata:
  name: task-card-cards-dp
  namespace: task-card
spec:
  selector:
    matchLabels:
      app: task-card-cards
  revisionHistoryLimit: 0
  template:
    metadata:
      labels:
        app: task-card-cards
        #tier: backend
        #service: users
    spec:
      containers:
      - name: task-card-cards-container
        image: luisavelino/task-card-cards:1.0
        imagePullPolicy: Always
        envFrom:
        #- secretRef:
        #    name: task-card-cards-sec
        - configMapRef:
            name: task-card-cards-cfg