apiVersion: apps/v1
kind: Deployment
metadata:
  name: task-card-cards-dp
  namespace: task-card
  labels:
    app: task-card-cards
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: task-card-cards
      version: v1
  template:
    metadata:
      labels:
        app: task-card-cards
        version: v1
    spec:
      serviceAccountName: task-card-task-card-cards
      containers:
      - name: task-card-cards
        image: luisavelino/task-card-cards:1.0
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: tmp
          mountPath: /tmp
        securityContext:
          runAsUser: 1000
        envFrom:
        #- secretRef:
        #    name: task-card-cards-sec
        - configMapRef:
            name: task-card-cards-cfg
      volumes:
      - name: tmp
        emptyDir: {}
