apiVersion: v1
kind: Service
metadata:
  name: task-card-users
  namespace: task-card
  labels:
    app: task-card-users
    service: task-card-users
spec:
  ports:
  - port: 8080
    name: http
  selector:
    app: task-card-users