apiVersion: v1
kind: Service
metadata:
  name: task-card-users-svc
  namespace: task-card
spec:
  type: NodePort
  ports:
    - port: 80
      nodePort: 30080
      name: http
  selector:
    app: task-card-users