apiVersion: v1
kind: Service
metadata:
  name: zookeeper
  namespace: task-card
  labels:
    app: zookeeper
    service: zookeeper
spec:
  ports:
  - port: 2181
    name: http
  selector:
    app: zookeeper