apiVersion: apps/v1
kind: Deployment
metadata:
  name: zookeeper-dp
  namespace: task-card
  labels:
    app: zookeeper
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zookeeper
      version: v1
  template:
    metadata:
      labels:
        app: zookeeper
        version: v1
    spec:
      serviceAccountName: task-card-zookeeper
      containers:
      - name: zookeeper
        image: confluentinc/cp-zookeeper:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: tmp
          mountPath: /tmp
        securityContext:
          runAsUser: 1000
        envFrom:
        #- secretRef:
        #    name: zookeeper-sec
        - configMapRef:
            name: zookeeper-cfg
      volumes:
      - name: tmp
        emptyDir: {}
