definitions:
  globals.BaseRequestReturn:
    properties:
      message:
        type: string
      status:
        type: string
    type: object
  models.User:
    properties:
      email:
        type: string
      id:
        type: integer
      role_id:
        type: integer
      username:
        maxLength: 40
        minLength: 3
        type: string
      userpass:
        type: string
    type: object
info:
  contact: {}
paths:
  /users:
    get:
      consumes:
      - application/json
      description: Route to get all users
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.User'
            type: array
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/globals.BaseRequestReturn'
      summary: Get all users
      tags:
      - users
    post:
      consumes:
      - application/json
      description: Route to create a new user
      parameters:
      - description: Username
        in: formData
        name: username
        required: true
        type: string
      - description: Userpass
        in: formData
        name: userpass
        required: true
        type: string
      - description: Email
        in: formData
        name: email
        required: true
        type: string
      - description: Role Id
        in: formData
        name: role_id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/globals.BaseRequestReturn'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/globals.BaseRequestReturn'
      summary: Create new user
      tags:
      - users
  /users/{id}:
    delete:
      consumes:
      - application/json
      description: Route to delete a user
      parameters:
      - description: User Id
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/globals.BaseRequestReturn'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/globals.BaseRequestReturn'
      summary: Delete a user
      tags:
      - users
    get:
      consumes:
      - application/json
      description: Route to get a user
      parameters:
      - description: User Id
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.User'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/globals.BaseRequestReturn'
      summary: Get a user
      tags:
      - users
    patch:
      consumes:
      - application/json
      description: Route to update a user
      parameters:
      - description: User Id
        in: path
        name: id
        required: true
        type: integer
      - description: User Name
        in: formData
        name: username
        required: true
        type: string
      - description: User Password
        in: formData
        name: userpass
        required: true
        type: string
      - description: User Email
        in: formData
        name: email
        required: true
        type: string
      - description: Role Id
        in: formData
        name: role_id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/globals.BaseRequestReturn'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/globals.BaseRequestReturn'
      summary: Update a user
      tags:
      - users
swagger: "2.0"
