definitions:
  request.ActionRequest:
    properties:
      user_id:
        type: integer
    required:
    - user_id
    type: object
  request.CardRequest:
    properties:
      card_status:
        type: string
      due_date:
        type: string
      summary:
        maxLength: 2500
        type: string
      title:
        type: string
      user_id:
        type: integer
    required:
    - card_status
    - summary
    - title
    - user_id
    type: object
  response.CardResponse:
    properties:
      card_status:
        type: string
      due_date:
        type: string
      id:
        type: integer
      summary:
        type: string
      title:
        type: string
      user_id:
        type: integer
    type: object
  rest_err.Causes:
    properties:
      field:
        type: string
      message:
        type: string
    type: object
  rest_err.RestErr:
    properties:
      causes:
        items:
          $ref: '#/definitions/rest_err.Causes'
        type: array
      code:
        type: integer
      error:
        type: string
      message:
        type: string
    type: object
  rest_success.BaseRequestReturn:
    properties:
      message:
        type: string
      status:
        type: string
    type: object
info:
  contact: {}
paths:
  /cards:
    get:
      consumes:
      - application/json
      description: Get all cards
      parameters:
      - description: Action info
        in: body
        name: action
        required: true
        schema:
          $ref: '#/definitions/request.ActionRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/response.CardResponse'
            type: array
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/rest_err.RestErr'
      summary: Get all cards
      tags:
      - cards
    post:
      consumes:
      - application/json
      description: Route to update a card
      parameters:
      - description: Card info
        in: body
        name: card
        required: true
        schema:
          $ref: '#/definitions/request.CardRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/rest_success.BaseRequestReturn'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/rest_err.RestErr'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/rest_err.RestErr'
      summary: Create a card
      tags:
      - cards
  /cards/{id}:
    delete:
      consumes:
      - application/json
      description: Delete a card
      parameters:
      - description: Card id
        in: path
        name: id
        required: true
        type: integer
      - description: Action info
        in: body
        name: action
        required: true
        schema:
          $ref: '#/definitions/request.ActionRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/rest_success.BaseRequestReturn'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/rest_err.RestErr'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/rest_err.RestErr'
      summary: Delete a card
      tags:
      - cards
    get:
      consumes:
      - application/json
      description: Get a card
      parameters:
      - description: Card id
        in: path
        name: id
        required: true
        type: integer
      - description: Action info
        in: body
        name: action
        required: true
        schema:
          $ref: '#/definitions/request.ActionRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/response.CardResponse'
            type: array
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/rest_err.RestErr'
      summary: Get a card
      tags:
      - cards
    post:
      consumes:
      - application/json
      description: Move a card
      parameters:
      - description: Card id
        in: path
        name: id
        required: true
        type: integer
      - description: Action info
        in: body
        name: action
        required: true
        schema:
          $ref: '#/definitions/request.ActionRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/rest_success.BaseRequestReturn'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/rest_err.RestErr'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/rest_err.RestErr'
      summary: Move a card
      tags:
      - cards
    put:
      consumes:
      - application/json
      description: Update a card
      parameters:
      - description: Card id
        in: path
        name: id
        required: true
        type: integer
      - description: Card info
        in: body
        name: card
        required: true
        schema:
          $ref: '#/definitions/request.CardRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/rest_success.BaseRequestReturn'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/rest_err.RestErr'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/rest_err.RestErr'
      summary: Update a card
      tags:
      - cards
swagger: "2.0"
